import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import CoffeeStoreData from "../data/coffee-stores.json";
import { fetchCoffeeStore } from "../lib/coffee-store";
import useTrackLocation from "../hooks/use-track-location";
import { useEffect, useState } from "react";
import { ACTION_TYPES, StoreContext } from "../pages/_app";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const CoffeeStore = await fetchCoffeeStore();
  return {
    props: {
      CoffeeStore,
    },
  };
}

export default function Home(props) {
  const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
    useTrackLocation();
  //console.log({handleTrackLocation });
  //console.log(props);
  const onCLickHandler = () => {
    console.log("hii");
    // console.log({ latLong, locationErrorMsg });
    handleTrackLocation();
  };

  const { dispatch, state } = useContext(StoreContext);
  const { coffeeStores, lat, lng } = state;
  //console.log("hi",lat)
  console.log({ lat });

  // const [coffeestores, setCoffeeStores] = useState("");
  const [coffeestoreerror, setCoffeeStoreError] = useState(null);
  useEffect(() => {
    const fetchData = async () => {
      if (lat && lng) {
        try {
          //console.log(lat.latitude);
          const fetchedCoffeeStores = await fetchCoffeeStore(
            lat.latitude.toString(),
            lng.longitude.toString(),
            30
          );
          console.log({ fetchedCoffeeStores });
          dispatch({
            type: ACTION_TYPES.SET_COFFEE_STORES,
            payload: {
              coffeeStores: fetchedCoffeeStores,
            },
          });
          // setCoffeeStores(fetchedCoffeeStores);
        } catch (err) {
          setCoffeeStoreError(err.message);
        }
      }
    };
    fetchData();
  }, [dispatch, lat, lng]);

  return (
    <div className={styles.container}>
      <Head>
        <title>CLOSEST CUP</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonTxt={isFindingLocation ? "Locating" : "View Shops Nearby"}
          handleOnClick={onCLickHandler}
        />
        {locationErrorMsg && <p>Something Went Wrong</p>}
        {coffeestoreerror && <p>Something Went Wrong</p>}
        <Image
          className={styles.heroImage}
          src="/static/hero-image.png"
          width={700}
          height={400}
          alt="heroimage"
        />

        {coffeeStores.length > 0 && (
          <>
            <div className={styles.sectionwrapper}>
              <h2 className={styles.heading2}>COFFEE STORES NEAR ME</h2>
              <div className={styles.cardLayout}>
                {coffeeStores.map((cfs) => {
                  return (
                    <Card
                      key={cfs.fsq_id}
                      name={cfs.name}
                      imageUrl={
                        cfs.imgUrl ||
                        "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                      }
                      href={`/coffee-store/${cfs.fsq_id}`}
                      className={styles.card}
                    />
                  );
                })}
              </div>
            </div>
          </>
        )}

        {props.CoffeeStore.length > 0 && (
          <>
            <div className={styles.sectionwrapper}>
              <h2 className={styles.heading2}>Dehradun</h2>
              <div className={styles.cardLayout}>
                {props.CoffeeStore.map((cfs) => {
                  return (
                    <Card
                      key={cfs.fsq_id}
                      name={cfs.name}
                      imageUrl={
                        cfs.imgUrl ||
                        "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                      }
                      href={`/coffee-store/${cfs.fsq_id}`}
                      className={styles.card}
                    />
                  );
                })}
              </div>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
